//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssignBuildingStylesWinForms.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AssignBuildingStylesWinForms.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value cannot be empty..
        /// </summary>
        internal static string ChooseStyleAddEmptyTextBox {
            get {
                return ResourceManager.GetString("ChooseStyleAddEmptyTextBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide Add Style Controls.
        /// </summary>
        internal static string ChooseStyleHideAddStyleText {
            get {
                return ResourceManager.GetString("ChooseStyleHideAddStyleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The building style id must be a hexadecimal number. E.g. 0x2000..
        /// </summary>
        internal static string ChooseStyleInvalidStyleId {
            get {
                return ResourceManager.GetString("ChooseStyleInvalidStyleId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Add Style Controls.
        /// </summary>
        internal static string ChooseStyleShowAddStyleText {
            get {
                return ResourceManager.GetString("ChooseStyleShowAddStyleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The installation and user plugin paths should be configured in the options dialog..
        /// </summary>
        internal static string ConfigureOptionsText {
            get {
                return ResourceManager.GetString("ConfigureOptionsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory: {0}.
        /// </summary>
        internal static string DirectoryFormat {
            get {
                return ResourceManager.GetString("DirectoryFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide Details.
        /// </summary>
        internal static string ErrorTaskDialog_HideDetails {
            get {
                return ResourceManager.GetString("ErrorTaskDialog_HideDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Details.
        /// </summary>
        internal static string ErrorTaskDialog_ShowDetails {
            get {
                return ResourceManager.GetString("ErrorTaskDialog_ShowDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The building style ids must be hexadecimal numbers with commas used as separators when entering multiple styles. E.g. 0x2000,0x2001..
        /// </summary>
        internal static string StyleTextBoxError {
            get {
                return ResourceManager.GetString("StyleTextBoxError", resourceCulture);
            }
        }
    }
}
